# This is a sample of a config file

# Fill the directories of each picture to be concatenated here
pictures:
  - "./sample_pic/1.jpg"
  - "./sample_pic/2.jpg"
  - "./sample_pic/3.jpg"
  - "./sample_pic/4.jpg"

# Fill the names of each picture here, which will be drawn on the top of each picture
names:
  - "The first."
  - "The second."
  - "The third."
  - "The fourth."

# Fill the output configurations
output_width: 1024
filling_color: "white"
output: "./sample_output/output.jpg"

# Center picture configs
center:
  # The directory of the background picture
  background_dir: "./sample_pic/center_bg.jpg"
  # Generate a new one with use the already existing one (will use the background only)
  generate_new: True
  # The parameters below are only available when generating_new == True
  size: 1024
  background_alpha: 0.25
  background_color: "white"
  # Config caption
  caption_text: "Caption"
  caption_font: "msyhbd"
  caption_fontsize: 120
  caption_color: "white"
  caption_offset: 25
  # Config subtitle
  subtitle_text: "This is a subtitle."
  subtitle_font: "msyh"
  subtitle_fontsize: 50
  subtitle_color: "white"

# Other picture configs
others:
  name_font: "msyh"
  name_fontsize: 20
  name_color: "white"
  name_bg_color: "black"

  
  
  